## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  # - osx
julia:
  - 0.7
  - '1.0'
  # - nightly
env:
  global:
    # Suppress "Could not connect to display" warnings from GR Framework.
    # * https://gr-framework.org/about.html#file-formats
    # * https://github.com/jheinen/gr/blob/v0.31.1/lib/gks/util.c#L67
    - GKS_WSTYPE: png
  matrix:
    - CI_GROUP=0
    - CI_GROUP=1
    - CI_GROUP=2
    - CI_GROUP=docs
notifications:
  email: false
git:
  depth: 99999999

matrix:
  allow_failures:
    - julia: '1.0'
      env: CI_GROUP=docs

## uncomment and modify the following lines to manually install system packages
#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran

before_script:
  - julia --color=yes ci/before_script.jl

script:
  - if [ "$CI_GROUP" = docs ]; then
    travis_wait 60 julia --color=yes docs/build.jl;
    else
    julia --color=yes --check-bounds=yes -e 'using Pkg; Pkg.test(coverage=true)';
    fi

after_success:
  - cat Manifest.toml
  # push coverage results to Coveralls
  - julia --color=yes -e 'using Pkg; cd(Pkg.dir("Bifurcations")); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia --color=yes -e 'using Pkg; cd(Pkg.dir("Bifurcations")); using Coverage; Codecov.submit(Codecov.process_folder())'
  # build documents
  - if [ "$CI_GROUP" = docs ]; then
    julia --color=yes docs/deploy.jl;
    fi
