site_name:        Bifurcations.jl
repo_url:         https://github.com/tkf/Bifurcations.jl
site_description: Bifurcation analysis in pure Julia
site_author:      tkf

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'
edit_uri: 'blob/master/docs/src'

pages:
  - Home: index.md
  - API: api.md
  - Internals: internals.md
  - Examples:
    - examples.md
    - examples/calcium.md
    - examples/van_der_pol.md
    - examples/morris_lecar.md
